use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Harbor 上的项目详情  
/// Generated by https://quicktype.io
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ProjectDetail {
    #[serde(rename = "digest")]
    digest: String,

    #[serde(rename = "name")]
    pub name: String,

    #[serde(rename = "size")]
    size: i64,

    #[serde(rename = "architecture")]
    architecture: String,

    #[serde(rename = "os")]
    os: String,

    #[serde(rename = "os.version")]
    os_version: String,

    #[serde(rename = "docker_version")]
    docker_version: String,

    #[serde(rename = "author")]
    author: String,

    #[serde(rename = "created")]
    created: String,

    #[serde(rename = "config")]
    config: Config,

    #[serde(rename = "immutable")]
    immutable: bool,

    #[serde(rename = "signature")]
    signature: Option<serde_json::Value>,

    #[serde(rename = "labels")]
    labels: Vec<Option<serde_json::Value>>,

    #[serde(rename = "push_time")]
    pub push_time: DateTime<Utc>,

    #[serde(rename = "pull_time")]
    pull_time: DateTime<Utc>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Config {
    #[serde(rename = "labels")]
    labels: Labels,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Labels {
    #[serde(rename = "maintainer")]
    maintainer: String,
}
